- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/drafts/__init__.py
- invenio_drafts_resources/drafts/api.py
- invenio_drafts_resources/drafts/models.py
- invenio_drafts_resources/ext.py
- invenio_drafts_resources/resources/draft.py
- invenio_drafts_resources/service/__init__.py
- invenio_drafts_resources/service/permission.py
- invenio_drafts_resources/service/schemas/__init__.py
- invenio_drafts_resources/service/schemas/json.py
- invenio_drafts_resources/service/service.py
- requirements-devel.txt
- setup.py
- tests/conftest.py
- tests/test_draft_resource.py
- tests/test_file_resource.py
**Continue in a new PR #4 to make work easier in diff branches**
*Disclaimer*: The objective of this PR is to merely separate DBs. There are many things "re-used" from records that might need change.
Requires the update of the singleton view in flask-resources
How the DB looks like (Some changes are needed to the db structure indeed):
Created draft:
> service: create draft

- invenio_drafts_resources/resource_units.py
- invenio_drafts_resources/serializers.py
- invenio_drafts_resources/version.py
- setup.py
These are just minor adjustments to make the release possible. Will merge, but I made a couple issues in this repository to cover what would need to be done next month.
> Release v0.1.1

- CHANGES.rst
- invenio_drafts_resources/services/draft.py
- invenio_drafts_resources/version.py
- tests/conftest.py
> Circular import fix

- setup.py
> fix titleized name

- setup.py
- tests/mock_module/api.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/62
> Fixes tests with is_delete

- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- run-tests.sh
- setup.py
- tests/conftest.py
- tests/records/conftest.py
- tests/records/test_api.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
- closes #81 
- :warning: requires https://github.com/inveniosoftware/invenio-records-resources/pull/173
- starts December release line: 0.7.x
> services: relax save conditions but validate when publishing

- invenio_drafts_resources/records/api.py
> records: add draft pid provider

- invenio_drafts_resources/services/records/components.py
- invenio_drafts_resources/services/records/config.py
- invenio_drafts_resources/version.py
- setup.py
- tests/conftest.py
- tests/resources/conftest.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/185
> services: remove empty record components

- invenio_drafts_resources/resources/records/config.py
- invenio_drafts_resources/resources/records/resource.py
- invenio_drafts_resources/services/records/schema.py
- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- setup.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
Closes inveniosoftware/invenio-rdm-records#324
Depends on Invenio-Records-Release and Flask-Resources.
> tests: fix broken tests

- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- setup.py
* Fixes issue with "es_preference" being included in the links.
> release: 0.8.2

- invenio_drafts_resources/resources/records/config.py
- invenio_drafts_resources/services/records/service.py
- tests/resources/test_record_resource.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/563
> service: support passing index as an argument to the search method

- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- setup.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/563
> service: pass default_filter for records and drafts search

- .github/workflows/tests.yml
- invenio_drafts_resources/records/__init__.py
- invenio_drafts_resources/records/api.py
- invenio_drafts_resources/records/models.py
- invenio_drafts_resources/records/systemfields/__init__.py
- invenio_drafts_resources/records/systemfields/parent.py
- invenio_drafts_resources/services/records/components.py
- invenio_drafts_resources/services/records/service.py
- setup.py
- tests/mock_module/api.py
- tests/mock_module/jsonschemas/records/parent-v1.0.0.json
- tests/mock_module/models.py
- tests/records/conftest.py
- tests/records/test_api.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
⚠️ Depends on https://github.com/inveniosoftware/invenio-records/pull/249
closes inveniosoftware/invenio-rdm-records#104
> records: initial versioning support in data layer

- setup.py
closes inveniosoftware/invenio-rdm-records/issues/444
remove invenio-pidrelations from the dependencies
> setup: remove invenio-pidrelations as a dependency

- invenio_drafts_resources/services/records/service.py
- setup.py
closes inveniosoftware/invenio-rdm-records#441
requires inveniosoftware/invenio-records-resources/pull/211
> 441 reindex everything

- invenio_drafts_resources/resources/records/config.py
- invenio_drafts_resources/resources/records/errors.py
- invenio_drafts_resources/resources/records/resource.py
- invenio_drafts_resources/resources/records/schemas_links.py
- invenio_drafts_resources/services/records/service.py
- tests/mock_module/resource.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
closes inveniosoftware/invenio-app-rdm#707
> records-versions: redirect to record latest version

- invenio_drafts_resources/records/__init__.py
- invenio_drafts_resources/records/models.py
- invenio_drafts_resources/records/systemfields/versions.py
- invenio_drafts_resources/services/records/schema.py
- tests/mock_module/mappings/v6/draftsresources/drafts/draft-v1.0.0.json
- tests/mock_module/mappings/v6/draftsresources/records/record-v1.0.0.json
- tests/mock_module/mappings/v7/draftsresources/drafts/draft-v1.0.0.json
- tests/mock_module/mappings/v7/draftsresources/records/record-v1.0.0.json
- tests/records/test_api.py
- tests/services/test_record_service.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/459
> versioning: rename parent_index to index

- invenio_drafts_resources/records/api.py
- invenio_drafts_resources/services/records/config.py
- invenio_drafts_resources/services/records/service.py
closes inveniosoftware/invenio-rdm-records#436
> api: add method to get all sibling records by their parent

- invenio_drafts_resources/services/records/results.py
- invenio_drafts_resources/services/records/service.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/463 (part of closing)
> versioning: provide different list_result for search_versions

- invenio_drafts_resources/services/records/config.py
- invenio_drafts_resources/services/records/search_params.py
- invenio_drafts_resources/services/records/service.py
- tests/services/conftest.py
- tests/services/test_record_service_search.py
- by default, filter for latest version
- if 'allversions' search parameter is truthy, show all versions
- closes #722 (backend)
> search: incorporate versions to search [+]

- invenio_drafts_resources/services/records/service.py
- depends on https://github.com/inveniosoftware/invenio-records-resources/pull/217
> schema: update according to records-resources refactor

- invenio_drafts_resources/version.py
- setup.py
- tests/resources/test_resource_links.py
* Closes inveniosoftware/invenio-records-resources#221
Blocked by https://github.com/inveniosoftware/invenio-records-resources/pull/222.
> config: harmonise hostname to 127.0.0.1

- invenio_drafts_resources/services/records/service.py
> service: remove update() method

- invenio_drafts_resources/records/__init__.py
- invenio_drafts_resources/records/api.py
- invenio_drafts_resources/services/records/components.py
- invenio_drafts_resources/services/records/config.py
- invenio_drafts_resources/services/records/schema.py
- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- setup.py
- tests/conftest.py
- tests/mock_module/api.py
- tests/mock_module/models.py
- tests/mock_module/permissions.py
- tests/mock_module/schemas.py
- tests/mock_module/service.py
- tests/records/conftest.py
- tests/records/test_api.py
- tests/resources/test_record_resource.py
- tests/resources/test_resource_links.py
- tests/services/__init__.py
- tests/services/conftest.py
- tests/services/test_record_service.py
- tests/services/test_record_service_search.py
- tests/services/utils.py
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/231 to be merged and released
- closes inveniosoftware/invenio-rdm-records#498
> files: validate files when updating/publishing draft

- invenio_drafts_resources/services/records/components/files.py
- invenio_drafts_resources/version.py
- setup.py
- tests/mock_module/schemas.py
- tests/services/test_record_service_files.py
> files: set default_preview via draft API

- invenio_drafts_resources/version.py
- setup.py
- tests/resources/conftest.py
- tests/services/conftest.py
- tests/services/test_record_service_files.py
closes inveniosoftware/invenio-records-resources#246
Depends on records-resources v0.15.3
> tests: register services

- invenio_drafts_resources/resources/records/resource.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/729
> resources: parse read_args

- .gitignore
- invenio_drafts_resources/translations/messages.pot
Todo:
* create a new resource for this module in transifex
* push the .pot file to created resource on transifex
> i18n: extract strings for translation

- invenio_drafts_resources/services/records/service.py
*closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1051
> service: add validate_draft

- invenio_drafts_resources/services/records/tasks.py
- tests/services/test_record_service_tasks.py
* closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/158
> celery: refactor to use service registry

- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/services/records/tasks.py
- invenio_drafts_resources/version.py
- tests/services/test_record_service_tasks.py
- service: add validate_draft
- celery: refactor to use service registry
- release: v0.13.6
> cherry pick 0.13.6

- invenio_drafts_resources/resources/records/resource.py
- invenio_drafts_resources/services/records/service.py
- invenio_drafts_resources/version.py
- tests/services/test_record_service.py
- tests/services/test_record_service_files.py
- tests/services/test_record_service_search.py
- tests/services/test_record_service_tasks.py
- tests/services/test_services.py
- tests/services/utils.py
- closes https://github.com/inveniosoftware/invenio-records-resources/issues/258
- dependencies: bump invenio-records-resources
- services: order methods to pass identity first
- release: v0.15.0
> 258 refactor service method parameters order

- invenio_drafts_resources/records/api.py
Previously, the operation would fail if the record versioning information still points to the drafts in question (foreign key violation).
Thus, we need to clean up the versioning information for the drafts in question (although I'm not 100% sure if the API class is the correct place to do this?).
closes #178
> api: fix cleanup_drafts

- invenio_drafts_resources/services/records/schema.py
* Needed by https://github.com/inveniosoftware/invenio-app-rdm/pull/1300
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1297
Updates record schema to dump if it's a draft.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s …
> schema: dump is_draft

- invenio_drafts_resources/services/records/config.py
- tests/services/test_record_service_search.py
closes #180 
Set `params_interpreters` of search options used by `search_versions` method.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions …
> fix: retrieve all versions by default

- invenio_drafts_resources/services/records/components/__init__.py
- invenio_drafts_resources/services/records/components/relations.py
- setup.py
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/312
- requires https://github.com/inveniosoftware/invenio-drafts-resources/pull/188 (build fix)
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/926
> service: add relations component

- invenio_drafts_resources/services/records/tasks.py
- tests/services/test_record_service_tasks.py
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/931
> global: rename registered services

- invenio_drafts_resources/records/api.py
- invenio_drafts_resources/services/records/service.py
- tests/records/test_api.py
> service: get related record to reindex when not deleted

- babel.ini
- invenio_drafts_resources/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: update .pot

- docs/conf.py
- invenio_drafts_resources/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: adds german translations

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/214
> release: v1.0.2

- invenio_drafts_resources/services/records/service.py
* Closes https://github.com/inveniosoftware/invenio-records-resources/issues/431.
* Use a lighter SQL query for fetching record IDs.
* Pass a generator to the bulk indexing call.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-und …
> services: fix rebuild index memory usage

- invenio_drafts_resources/services/records/components/files.py
- tests/conftest.py
- tests/services/test_record_service_files.py
* closes https://github.com/inveniosoftware/invenio-drafts-resources/issues/219
> files: publishing files pending download from Fetch #219

- invenio_drafts_resources/services/records/service.py
UPDATE: I decided to go with the second approach outlined in the other comment, because I feel that avoiding errors is the more sensible approach than catching and ignoring these errors.
The original text for this PR was as follows:
---
The `validate_draft` needs to `schema.load(...)` the (already stored) metadata instead of `schema.dump(...)`, because the latter [does not validate the object to serialize anymore since version 3.0.0rc9](https://github.com/marshmallow-code/marshmallow/blob/dev/src/marshmallow/schema.py#L546-L547).
However, the `RDMRecordSchema` defines [field-level permissions for loading](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/__init__.py#L45-L47).
This is usually okay because it is typically just the …
> Fix `preview` permissions: Add flag to skip checking of field-level load permissions in `validate_draft`

- invenio_drafts_resources/services/records/components/files.py
- tests/services/test_record_service_files.py
* Returns permission errors only when the input actually tries to modify files options.
**Reminder**
1. You license your contribution under the same …
> files: fix error message for metadata-only toggle

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- setup.cfg
> release: v1.2.0

- invenio_drafts_resources/services/records/service.py
- setup.cfg
- tests/mock_module/api.py
- tests/services/test_record_service_files.py
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
> tests: ensure file metadata indexing is tested

- invenio_drafts_resources/services/records/components/pid.py
- tests/services/test_record_service.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1281.
> pid: fix parent PID status for record deletion

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/services/records/components/files.py
Addresses https://github.com/inveniosoftware/invenio-rdm-records/issues/1314
> files: pass record to manage files permission check

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/services/records/components/files.py
- tests/mock_module/service.py
* closes https://github.com/zenodo/who-rdm/issues/71
> components: merge files components

- invenio_drafts_resources/records/api.py
- invenio_drafts_resources/records/systemfields/versions.py
- invenio_drafts_resources/services/records/service.py
- tests/records/test_api.py
- Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1282.
- versions: add parent ID resolver
- api: return generator for record versions
> Resolve parent IDs

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.6.0

- invenio_drafts_resources/services/records/service.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
* Allows to fetch the latest version by passing the parent id
* closes https://github.com/zenodo/rdm-project/issues/174
> service: improve read_latest

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.8.0

- invenio_drafts_resources/services/records/service.py
* closes https://github.com/inveniosoftware/invenio-records-resources/issues/486
Note: the only usage: https://github.com/inveniosoftware/invenio-rdm-records/blob/0728b74cfd98c92616485b71d259fc224a8a60f9/invenio_rdm_records/requests/user_moderation/actions.py#L32
> services: move reindex latest records from records-resources

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.8.1

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- setup.cfg
To require the backported file fixes
> Bump Invenio-Records-Resources

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.9.0

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.10.1

- invenio_drafts_resources/resources/records/resource.py
closes https://github.com/zenodo/rdm-project/issues/258
> resources: add etag headers

- invenio_drafts_resources/resources/records/args.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1494
> resources: rename search request argument

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.11.1

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.12.0

- invenio_drafts_resources/services/records/service.py
> service: allow passing permission_action in kwargs for search versions

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v1.12.1

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/services/records/components/media_files.py
- tests/services/test_record_service_files.py
* closes https://github.com/zenodo/rdm-project/issues/365
> Recreate missing buckets

- invenio_drafts_resources/services/records/components/base.py
- invenio_drafts_resources/services/records/config.py
* closes https://github.com/zenodo/rdm-project/issues/398
> components: enrich file lock function

- CHANGES.rst
- invenio_drafts_resources/__init__.py
> release: v2.0.1

- invenio_drafts_resources/services/records/components/base.py
* closes https://github.com/zenodo/rdm-project/issues/413
> components: use teardown for draft cleanup

- .github/workflows/tests.yml
- CHANGES.rst
- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/services/records/uow.py
- setup.cfg
> Bump dependencies and release v3.0.0

- .tx/config
- CHANGES.rst
- invenio_drafts_resources/__init__.py
- invenio_drafts_resources/services/records/components/media_files.py
- tests/services/test_record_service.py
- tests/services/test_record_service_files.py
- **media-files: prevent copying to new version**
- **📦 release: v3.1.0**
> Fix media files new version copy bug and release v3.1.0

- invenio_drafts_resources/services/records/components/base.py
- invenio_drafts_resources/services/records/config.py
closes https://github.com/zenodo/zenodo-rdm/issues/852
> services: fix permission for file edit.

- CHANGES.rst
- invenio_drafts_resources/__init__.py
- setup.cfg
- Bump major version of `invenio-records-resources`
> release: v4.0.0

- .github/workflows/tests.yml
- invenio_drafts_resources/resources/records/errors.py
- invenio_drafts_resources/services/records/service.py
- tests/mock_module/api.py
- tests/mock_module/models.py
- tests/resources/test_record_resource.py
- tests/services/test_record_service.py
- tests/services/utils.py
- tests: missing bucket on mock classes
- errors: introduce an error for drafts not found when publish record exists
> maint 3 cherry picked

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- CHANGES.rst
- invenio_drafts_resources/__init__.py
- setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v6.0.0
> bump major

- .gitignore
- invenio_drafts_resources/services/records/config.py
- tests/mock_module/service.py
> Please describe briefly your pull request.
1. The CI has been failing https://github.com/inveniosoftware/invenio-drafts-resources/actions/workflows/tests.yml
2. Used the .gitignore from records-resources
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
1. You …
> chore: isort and update gitignore

- invenio_drafts_resources/resources/records/errors.py
- invenio_drafts_resources/services/records/config.py
- invenio_drafts_resources/services/records/service.py
- setup.cfg
- tests/mock_module/service.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
> I18n-translations-backport

- invenio_drafts_resources/services/records/components/base.py
- invenio_drafts_resources/services/records/components/relations.py
- invenio_drafts_resources/services/records/service.py
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/2051
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder** …
> services: added errors in read_draft method
