invenio_drafts_resources/drafts/api.py, invenio_drafts_resources/drafts/models.py, invenio_drafts_resources/resources/draft.py, invenio_drafts_resources/services/draft.py, requirements-devel.txt, tests/conftest.py, tests/test_draft_resource.py, tests/test_draft_service.py
Requires:
- https://github.com/inveniosoftware/invenio-pidstore/pull/132
- https://github.com/inveniosoftware/invenio-records-resources/pull/43
- https://github.com/inveniosoftware/invenio-records-resources/pull/46
**Things that will be refactored with the new PID management, WIP in a different PR to be created**
Setting the provider status directly...
``` python
RecordIdProviderV2.default_status_with_obj = PIDStatus.NEW
```
Catching a SQLAlchemy exception (It has to do with how we handle publish draft pids).
```
with pytest.raises(NoResultFound):
```
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/210
=> publishing from drafts for new record.

invenio_drafts_resources/drafts/api.py, invenio_drafts_resources/services/draft.py, invenio_drafts_resources/version.py, setup.py
Previously the minting was happening after the the DB and therefore the `recid` was only present in the indexed content. Later on, when publishing the record was re-indexed without the `recid` (since at resolve time from db it was not there). This was causing problems in the search.
=> services, draft: fix minter order to add recid field to db content

invenio_drafts_resources/errors.py, invenio_drafts_resources/resources/draft.py, tests/conftest.py, tests/test_draft_resource.py
Requires #25 
**Note**:
It is not a fully-fledged command pattern. Implementing interfaces with "execute", invoker and receiver seemed a bit of an overkill for what we want: *Easy way to make actions configurable*
closes #31
=> Command patttern for DraftActionResource

invenio_drafts_resources/resources/draft_config.py
- closes #47 
- not crucial for release (temporary fix in invenio-rdm-records)
=> config: set default action_commands

invenio_drafts_resources/services/records/service.py, setup.py, tests/resources/test_record_resource.py, tests/services/test_record_service.py
requires https://github.com/inveniosoftware/invenio-records/pull/231
=> services: edit workflow and soft deletion of draft

invenio_drafts_resources/resources/records/resource.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/version.py, run-tests.sh, tests/mock_module/api.py, tests/records/test_api.py, tests/resources/test_record_resource.py
NOTE: In the future `service.py/search` might be able to use a parent sort of `_search` class like in `_create`.
=> global: enable search by record status

.gitignore, invenio_drafts_resources/services/records/schema.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/version.py, setup.py, tests/resources/test_record_resource.py
**EDIT Feb 18 2021**
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/214
- uses `draft_item.data` for validation via `schema.load`
- :warning: requires https://github.com/inveniosoftware/invenio-records-resources/pull/199 so will fail until that one is released
- the dates error is explicitly tested against in upcoming invenio-rdm-records PR
~~Trying to resolve https://github.com/inveniosoftware/react-invenio-deposit/issues/214
This strange behaviour (see comments) is happening (locally) and I can't put my finger on why. I am using the master branches of all dependencies. I even tried with Max's https://github.com/inveniosoftware/invenio-rdm-records/pull/383/files~~
=> service: validate saved data before publication

invenio_drafts_resources/services/records/components.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/version.py
* Ensures that record files, object versions and buckets are properly
removed when an unpublished record is removed.
* Fixes an issue where a draft could not be deleted due to database
integrity constraints.
=> services: unpublished drafts removes files

invenio_drafts_resources/services/records/service.py
* Refresh the index when deleting a record to ensure that a user won't
see the just deleted record in a search results afterwards.
=> services: refresh index on delete

invenio_drafts_resources/records/__init__.py, invenio_drafts_resources/records/api.py, invenio_drafts_resources/records/models.py, invenio_drafts_resources/records/systemfields/__init__.py, invenio_drafts_resources/records/systemfields/parent.py, invenio_drafts_resources/records/systemfields/versions.py, invenio_drafts_resources/services/records/components.py, invenio_drafts_resources/services/records/permissions.py, invenio_drafts_resources/services/records/schema.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/version.py, tests/mock_module/api.py, tests/mock_module/models.py, tests/mock_module/permissions.py, tests/records/test_api.py, tests/resources/test_record_resource.py, tests/services/test_record_service.py
closes inveniosoftware/invenio-rdm-records#435
This is the Draft-Resources part of versioning. The RDM-Records part is still missing, but this one can be reviewed independently from RDM-Records.
=> records/service: implement new version creation

invenio_drafts_resources/services/records/service.py
Check permission after we have retrieved the latest record as the user might not have access rights to get the latest record but indeed have rights to see the current record.
=> service: check permission after getting the latest record

invenio_drafts_resources/version.py
triggered by [release v0.35.4](https://github.com/inveniosoftware/invenio-rdm-records/commit/ba4707a7c3e10197f5fbb6c4f99b1631ae7f212c) of invenio-rdm-records which contains the service registration rename.
=> release: v0.16.2

invenio_drafts_resources/services/records/service.py, tests/mock_module/permissions.py, tests/services/test_record_service.py
Previously, the reindexing of related records only reindexed sibling *records* (i.e. records sharing the same parent), but not sibling *drafts*.
Thus, the indexed variants of sibling drafts would become outdated when something in their parents changed.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1228
=> Include drafts in reindexing of related records

invenio_drafts_resources/services/records/config.py, invenio_drafts_resources/services/records/service.py
Make the `service.rebuild_index` method utilize bulk indexing rather than indexing every item individually.
Also add a `draft_indexer` property to the service/config that is separate from the `indexer` property, because each indexer has a set `record_cls` which is used for looking up items to index by ID in bulk indexing.
This PR is related to https://github.com/inveniosoftware/invenio-records-resources/pull/419 ~and currently also includes the changes from https://github.com/inveniosoftware/invenio-drafts-resources/pull/207~.
=> Bulk indexing for `rebuild_index`

CHANGES.rst, invenio_drafts_resources/__init__.py, invenio_drafts_resources/services/records/components/files.py, invenio_drafts_resources/services/records/components/metadata.py, invenio_drafts_resources/services/records/components/pid.py, invenio_drafts_resources/services/records/config.py, run-tests.sh, setup.cfg
- migrate: flask_babelex replaced by invenio_i18n
- fix: --dry-run ignored
- NOTE: Flask-Security-Invenio invenio-accounts invenio-admin invenio-files-rest invenio-i18n invenio-pidstore invenio-records invenio-records-resources invenio-theme have to be released first
=> migrate to flask babel

invenio_drafts_resources/services/records/components/files.py, invenio_drafts_resources/services/records/permissions.py, tests/mock_module/permissions.py, tests/services/test_record_service_files.py
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2021.
> **Warning**
> ~~This is a breaking change, that will require a major bump release!~~ Actually, this is not the case anymore. By default metadata-only records are allowed, so unless someone explicitly changes this permission or the config flag in their instance, the old behaviour still applies (i.e. it's possible to disable files).
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
=> services: make files management permission-based

invenio_drafts_resources/records/api.py, invenio_drafts_resources/records/systemfields/versions.py, tests/records/test_api.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2197
Although small, the fix has a larger context to understand. When a record is published, its draft is soft-deleted in the db until `cleanup_drafts` hard deletes it. When that happens, the published record has no associated draft anymore, so `edit` will create a completely new draft for it. However, that record may have a new version already (this is a fairly common occurrence in a running instance), so the new draft must not overwrite the reference to the `next_draft_id` stored in the parent. Because `next_draft_id` is used both to refer to a record's next version and a never published before draft's own id, we get interference. By checking if we are in the case of a record that has been published (only records that can …
=> api: don't override next version with new draft

invenio_drafts_resources/services/records/components/base.py, invenio_drafts_resources/services/records/components/files.py, invenio_drafts_resources/services/records/components/media_files.py, invenio_drafts_resources/services/records/config.py, tests/mock_module/service.py, tests/resources/test_record_resource.py, tests/services/test_record_service.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2259
* requires https://github.com/inveniosoftware/invenio-records-resources/pull/479
Context:
new functionality is added, we need to use bucket syncing to copy over files edited in the draft (if editing is allowed)
=> components: lock files conditionally

invenio_drafts_resources/records/api.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/services/records/tasks.py, tests/services/test_record_service_tasks.py, tests/services/test_services.py
Soft deleted records are being kept in Opensearch for [60 seconds by default](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete.html#delete-versioning). That is happening for control of concurrent processes. In our case, when a soft deleted draft is cleaned up but it happened to be soft deleted in less than the time window that Opensearch finally cleans it up, then editing a new record is resulting in version conflict.
This PR adds a new kwarg to deduct the default deletion time and it can be passed as a parameter in case someone has configured the corresponding setting in a different value.
=> tasks: add margin time window for search to purge deleted documents

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, invenio_drafts_resources/services/records/service.py
Previously, the `service.read_drafts()` and `service.read_versions()` methods would not offer a possibility to specify `extra_filter` values that would be taken into account for the created search queries.
This would prevent the RDM-Records service to filter out _deleted records_ (not deleted drafts) from the user's dashboard.
In this PR, I merge the `kwargs["extra_filter"]` (if present) into the default one created in the `search_drafts()` and `read_versions()` methods respectively.
In this way, both the default filter as well as the custom one passed through the keyword arguments apply.
=> Record deletion: Allow passing of 'extra_filter' via kwargs to searches

.github/workflows/tests.yml, CHANGES.rst, invenio_drafts_resources/__init__.py, invenio_drafts_resources/records/api.py, invenio_drafts_resources/services/records/service.py, invenio_drafts_resources/services/records/uow.py, tests/records/test_api.py, tests/services/test_record_service.py, tests/services/test_records_uow.py
- adds a new uow to commit a parent record and bulk index all records and drafts
=> uow: add ParentRecordCommitOp uow

invenio_drafts_resources/services/records/components/base.py
* when file is being uploaded, if user tries to publish return validation error instead of 500
* closes https://github.com/zenodo/rdm-project/issues/253
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2220
this and dependent PRs need to be reviewed and tested **very** thoroughly
=> components: replace ambiguous error on publish

invenio_drafts_resources/services/records/service.py, tests/services/test_record_service.py
* Raise a proper error when trying to read a draft for a published record when it's not being edited (i.e draft doesn't exists).
=> service: error when published record without draft

invenio_drafts_resources/services/records/config.py
* functions bind to class attributes still get the self parameter which
is not present in the definition of the lock_edit_published_files
function. this result in `TypeError: lock_edit_published_files() got
multiple values for argument 'record'`. by marking it as a static
method the bind function will not get the self parameter anymore.
the full error is:
```
env/lib/python3.11/site-packages/invenio_drafts_resources/services/records/components/base.py", line 168, in edit
lock_files = self.service.config.lock_edit_published_files(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: lock_edit_published_files() got multiple values for argument 'record'
```
=> fix: TypeError multiple values for record

invenio_drafts_resources/resources/records/errors.py, invenio_drafts_resources/services/records/service.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2694
=> errors: introduce an error for drafts not found when published record exists

.github/workflows/tests.yml, invenio_drafts_resources/resources/records/resource.py
* closes https://github.com/zenodo/rdm-project/issues/598
=> http headers: use and adjust vnd.inveniordm.v1+json http accept header

invenio_drafts_resources/services/records/service.py, tests/mock_module/permissions.py
(see https://github.com/inveniosoftware/docs-invenio-rdm/pull/737#discussion_r2156833316 for context)
When implementing pluggable transfer types, permissions for the `init_files` call (`POST /.../files`) were updated to require file metadata. This ensures the system can verify whether the user has permission to use the selected transfer type (since permissions may vary by transfer type and each uploaded file can use different transfer type).  
However, the `import_files` call—which copies files from a published record to a new version of the same record—relies on the same permission check *without* passing individual files. As a result, permission checks fail (access denied) when transfer-specific permissions are enforced (e.g., in RDM).  
This PR changes the permission check to …
=> fix: import-files permissions
